### PR TITLE
Fixed non-functional links and buttons

### PR DESCRIPTION
**Pull request by harshjais369**
## Description of changes

This PR solves all non-functional links and buttons in the footer section and throughout the website. I've provided their corresponding relevant URLs for these elements, which have broughton back the intended functionality of the links and buttons.

## Walkthrough of changes

Video link: [click here](https://drive.google.com/file/d/1DogKDamwPpiz-nBVxPrY-wbBV_NtWZmg/view?usp=drivesdk)

After applying the changes aforementioned, this video above shows the demonstration of their functioning.

- **Related issue: #5**

### CODE REVIEW

**Comment by harshjais369** [comment]
Alright! On my way..

**Comment by harshjais369** [comment]
@CodeXstalker I have updated my above comment with all requirements. Please take a glance over it again.

**Comment by harshjais369** [comment]
Thanks for merging my PR!
Could you please take a moment and add "hacktoberfest-accepted" label to this PR?

**Comment by CodeXstalker** [comment]
done

**Pull request merged**
